name: Build and deploy to Hostinger

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy dist to Hostinger via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4

        with:
          server: ${{ secrets.HOSTINGER_FTP_HOST }}
          username: ${{ secrets.HOSTINGER_FTP_USER }}
          password: ${{ secrets.HOSTINGER_FTP_PASS }}
          port: 21
          protocol: ftp
          local-dir: dist/
          server-dir: public_html/
