name: Build and deploy to Hostinger (SFTP - fix 403)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      # 1) Prepara as duas pastas e remove index padrão da Hostinger
      - name: Prepare target folders (SSH)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOSTINGER_FTP_HOST }}     # 147.93.14.207
          username: ${{ secrets.HOSTINGER_FTP_USER }} # u234345696
          password: ${{ secrets.HOSTINGER_FTP_PASS }}
          port: 65002
          script: |
            set -e
            mkdir -p /home/u234345696/public_html
            mkdir -p /home/u234345696/domains/sejadigitalmarket.com/public_html
            rm -f /home/u234345696/public_html/index.html /home/u234345696/public_html/index.php || true
            rm -f /home/u234345696/domains/sejadigitalmarket.com/public_html/index.html /home/u234345696/domains/sejadigitalmarket.com/public_html/index.php || true

      # 2) Sobe o build nas duas possíveis raízes
      - name: Upload dist/ to ~/public_html (SFTP)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOSTINGER_FTP_HOST }}
          username: ${{ secrets.HOSTINGER_FTP_USER }}
          password: ${{ secrets.HOSTINGER_FTP_PASS }}
          port: 65002
          source: "dist/*"
          target: "/home/u234345696/public_html"
          overwrite: true

      - name: Upload dist/ to domain public_html (SFTP)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOSTINGER_FTP_HOST }}
          username: ${{ secrets.HOSTINGER_FTP_USER }}
          password: ${{ secrets.HOSTINGER_FTP_PASS }}
          port: 65002
          source: "dist/*"
          target: "/home/u234345696/domains/sejadigitalmarket.com/public_html"
          overwrite: true

      # 3) Cria .htaccess SPA e 4) corrige permissões
      - name: Add .htaccess and fix permissions (SSH)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOSTINGER_FTP_HOST }}
          username: ${{ secrets.HOSTINGER_FTP_USER }}
          password: ${{ secrets.HOSTINGER_FTP_PASS }}
          port: 65002
          script: |
            set -e
            for DIR in /home/u234345696/public_html /home/u234345696/domains/sejadigitalmarket.com/public_html; do
              cat > "$DIR/.htaccess" <<'EOF'
<IfModule mod_rewrite.c>
  RewriteEngine On
  RewriteBase /
  RewriteRule ^index\.html$ - [L]
  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteCond %{REQUEST_FILENAME} !-d
  RewriteRule . /index.html [L]
</IfModule>
EOF
              find "$DIR" -type d -exec chmod 755 {} \;
              find "$DIR" -type f -exec chmod 644 {} \;
            done
