name: Build and deploy to Hostinger (SFTP - domain path)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      # Cria a pasta do domínio e remove página padrão da Hostinger
      - name: Prepare target folder (SSH)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOSTINGER_FTP_HOST }}       # 147.93.14.207
          username: ${{ secrets.HOSTINGER_FTP_USER }}   # u234345696
          password: ${{ secrets.HOSTINGER_FTP_PASS }}
          port: 65002
          script: |
            mkdir -p /home/u234345696/domains/sejadigitalmarket.com/public_html
            rm -f /home/u234345696/domains/sejadigitalmarket.com/public_html/index.html \
                  /home/u234345696/domains/sejadigitalmarket.com/public_html/index.php || true

      # Envia o build (dist/) para a pasta correta do domínio
      - name: Upload dist/ via SFTP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOSTINGER_FTP_HOST }}
          username: ${{ secrets.HOSTINGER_FTP_USER }}
          password: ${{ secrets.HOSTINGER_FTP_PASS }}
          port: 65002
          source: "dist/*"
          target: "/home/u234345696/domains/sejadigitalmarket.com/public_html"
          overwrite: true
